<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUKaJ3YZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUKaJ3YZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUKaJ3YZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUKaJ3YZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUKaJ3YZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'UKaJ3YZ',
    'container.build_id' => '60016d08',
    'container.build_time' => 1718288485,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUKaJ3YZ');
